ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/static/
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true